boardSize: 10
players:
  - name: Gaurav
    currentPos: 1
  - name: Sagar
    currentPos: 1
snakes:
  - source: 62
    destination: 5
ladders:
  - source: 5
    destination: 62
crocodiles: []
mines: []
dices: [6, 5]
diceRolls:
movementStrategy: min
